### ISSUE TITLE
Mobile view of admin settings not rendering correctly

### ISSUE THREAD

**Issue by ElisabettaCarrara** [johnalarcon/wysiwyg-advanced#1]
Navigating to settings>wysiwyg from mobile results in a broken view as per screen shots
![screenshot_2019-01-23_173410](https://user-images.githubusercontent.com/38214395/51622208-6b46ae00-1f36-11e9-8427-458495793910.jpg)
![screenshot_2019-01-23_173405](https://user-images.githubusercontent.com/38214395/51622209-6b46ae00-1f36-11e9-8ea1-9c2bddaf2909.jpg)
![screenshot_2019-01-23_173418](https://user-images.githubusercontent.com/38214395/51622210-6bdf4480-1f36-11e9-9d05-fe0cb9e1aa30.jpg)
![screenshot_2019-01-23_173414](https://user-images.githubusercontent.com/38214395/51622211-6bdf4480-1f36-11e9-8c01-a396d38baf58.jpg)
![screenshot_2019-01-23_173424](https://user-images.githubusercontent.com/38214395/51622214-6bdf4480-1f36-11e9-9d11-d6fc49620aa2.jpg)
![screenshot_2019-01-23_173432](https://user-images.githubusercontent.com/38214395/51622215-6c77db00-1f36-11e9-9271-f9330cc94717.jpg)
![screenshot_2019-01-23_173428](https://user-images.githubusercontent.com/38214395/51622217-6d107180-1f36-11e9-850d-b81adee87300.jpg)
![screenshot_2019-01-23_173441](https://user-images.githubusercontent.com/38214395/51622219-6da90800-1f36-11e9-9d16-7292e8fb9f23.jpg)
![screenshot_2019-01-23_173435](https://user-images.githubusercontent.com/38214395/51622220-6da90800-1f36-11e9-8609-2f22572a1d44.jpg)
![screenshot_2019-01-23_173355](https://user-images.githubusercontent.com/38214395/51622221-6e419e80-1f36-11e9-9584-42a00288887e.jpg)

**Comment by johnalarcon** [comment]
Thanks for the report. This behavior also exists in the _TinyMCE Advanced_ plugin's admin settings page. Given the tiny viewport that it takes to break the display, and the fact that this page will likely be visited very few times, I think it's a livable issue. This only affects the settings page; the WYSIWYG editors themselves are fully responsive.
